### ISSUE TITLE
Error when Chinese background folder is selected

### ISSUE THREAD

**Issue by kirkins** [rickyhan/macintoshplus#4]
I found an error that occurs with the random seed generator. One file/folder is selected at random from `img/png/windows/`, there is only one folder `chinese` but if it gets selected the program errors.

Use this seed to reproduce issue:

    win_path = Random("jjjjjjkjkjjkjkjkjfkdjkjkjj").choice(macintoshplus.windows)

> img/png/windows/chinese
> Traceback (most recent call last):
>   File "demo.py", line 23, in <module>
>     win = Image.open(win_path).convert("RGBA")
>   File "/usr/lib/python2.7/site-packages/PIL/Image.py", line 2410, in open
>     fp = builtins.open(filename, "rb")
> IOError: [Errno 21] Is a directory: 'img/png/windows/chinese'

Possible solution: move contents of chinese folder into root?

**Comment by 0b01** [comment]
Yes that'll work. :+1:
